
# Use an official Python runtime as the parent image
FROM python:3.10-slim

# Set working directory in the container
WORKDIR /app

# Copy requirements file from project root
COPY requirements.txt /app/

# Copy code and data folders from project root
COPY src/py-code/ /app/src/py-code/
COPY src/data/ /app/src/data/

# Install dependencies
RUN pip install -r requirements.txt

# Make port 8888 available for Jupyter if needed
EXPOSE 8888

# Command to run scripts (default: main.py in code folder)
CMD ["python", "src/py-code/main.py"]

